language: generic
script:
 - export BASHUNIT_RELEASE="0.3.2"
 - wget -O "$HOME/bashunit.tar.gz" "https://github.com/athena-oss/bashunit/archive/v${BASHUNIT_RELEASE}.tar.gz" && tar -v -C "$HOME" -xzf "$HOME/bashunit.tar.gz" && mv "$HOME/bashunit-${BASHUNIT_RELEASE}" "$HOME/bashunit"
 - $HOME/bashunit/bashunit test
