#!/usr/bin/env bash
# This function tries to retrieve the current script directory.
# Case this script is a symlink, it will try to resolve it. If
# the script is a relative symlink it will resolve it relative
# to the symlink base directory.
# USAGE: bashog.get_current_script_dir
# RETURN: string
function bashog.get_current_script_dir()
{
	local src="${BASH_SOURCE[0]}"
	local dir

	# While $src is a symlink, resolve it
	while [ -h "$src" ]; do
	  dir="$( cd -P "$( dirname "$src" )" && pwd )"
	  src="$( readlink "$src" )"

	  # relative symlink
	  [[ $src != /* ]] && src="$dir/$src"
	done
	dir="$( cd -P "$( dirname "$src" )" && pwd )"
	echo "$dir"
}

curr_script_dir="$(bashog.get_current_script_dir)"
cat "${curr_script_dir}/.logo"
source "${curr_script_dir}/lib/functions.sh"

feed="$(pwd)/feed.hog"
if [ ! -f "$feed" ]; then
	bashog.print_error "feed.hog file not found."
fi

bashog.run "$feed"
